# Site settings
title: nickethier.
email: nick@nickethier.org
description: > # this means to ignore newlines until "baseurl:"
  Infrastructure coder by day, network hacker by night.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nickethier.org" # the base hostname & protocol for your site
twitter_username: nickethier
github_username:  nickethier

# Build settings
markdown: kramdown

paginate: 5
paginate_path: "blog/page:num/"

gems:
  - jekyll-sitemap
